### ISSUE TITLE
项目模板中使用了tslint，但是模板代码很多地方都没有符合规范

### ISSUE THREAD

**Issue by aasailan** [easy-team/egg-vue-typescript-boilerplate#1]
如题，结果就是用vscode打开模板项目的时候，到处都在报错。。。。如下图。希望作者在升级webpack4的时候，能不能顺便改一下ts的模板代码。嗨皮
![image](https://user-images.githubusercontent.com/12505615/37023922-724b575a-2162-11e8-9c49-4e346fa90616.png)
![image](https://user-images.githubusercontent.com/12505615/37023956-8c26bf52-2162-11e8-8462-220f4df15407.png)

**Comment by hubcarl** [comment]
@aasailan  好的

**Comment by hubcarl** [comment]
@aasailan 我本地vscode是OK

**Comment by hubcarl** [comment]
已重新调整格式
