### ISSUE TITLE
renderClient 问题

### ISSUE THREAD

**Issue by illusory-love** [easy-team/egg-vue-typescript-boilerplate#12]
这个模版能写两个最简单的demo么，我是第一次用，之前也没写过vue
在现有的模版中:
- ctx.render('admin/home.js') 过于复杂了（这个是一个SPA？），能否再写一个单页面的。
- ctx.renderClient('admin/login.js') 没有使用的代码，
  - 我在router定义路由访问 `router.get('/login', controller.admin.login)`，得到的是一个仅有 layout.html 里的公共代码的空白页面
  - 新建 renderClient 渲染的页面也全是仅有 layout.html 公共代码的空白页面

弄了几天了。还是没搞定

**Comment by hubcarl** [comment]
解决了没？
