### ISSUE TITLE
缺少简单的服务器渲染单页(不使用vuex和vue-router)例子

### ISSUE THREAD

**Issue by gzlock** [easy-team/egg-vue-typescript-boilerplate#13]
想根据`app/web/page/admin/home/`的例子来改，结果焦头烂额

希望可以增加一个简单的不使用vuex和vue-router的服务器单页渲染例子

**Comment by hubcarl** [comment]
@gzlock 对比看一下https://github.com/easy-team/egg-vue-webpack-boilerplate

**Comment by gzlock** [comment]
发issue前有对比过的，ts和js两个boilerplate `app/web/framework`里的架构有很大的差别(ts就一个app.ts，js里有很多文件)，没办法作为参考

**Comment by hubcarl** [comment]
@gzlock 看一下 master ，增加了一个 login 页面

**Comment by hubcarl** [comment]
see awesome branch
