### ISSUE TITLE
egg2.6 TypeScript tool support，是否有计划更新ts版的脚手架

### ISSUE THREAD

**Issue by ZQun** [easy-team/egg-vue-typescript-boilerplate#2]
https://github.com/eggjs/egg/issues/2272

egg2.6 TypeScript tool support，是否有计划更新ts版的脚手架

**Comment by hubcarl** [comment]
master 代码已更新为 ts版的脚手架

**Comment by ZQun** [comment]
😂😉要不要基于https://github.com/midwayjs/midway 集成一下～ @hubcarl
