### ISSUE TITLE
typescript版本无法集成：sequelize-typescript

### ISSUE THREAD

**Issue by elvisqi** [easy-team/egg-vue-typescript-boilerplate#3]
使用了typescript版本，但是无法集成：sequelize-typescript

![image](https://user-images.githubusercontent.com/3584916/39669852-748fa29e-512a-11e8-9ea5-d9188e4fd31c.png)

看起来并没有集成 egg官方的typescript方案，如：egg-bin dev -r egg-ts-helper/register

**Comment by hubcarl** [comment]
@elvisqi  这是早期的方案，你可以 PR 一个

**Comment by hubcarl** [comment]
@elvisqi  已经集成官方typescript，并且前后端都是用 TypeScript 编写
