### ISSUE TITLE
请问有考虑集成typeORM吗

### ISSUE THREAD

**Issue by hsuanyi-chou** [easy-team/egg-vue-typescript-boilerplate#4]
eggjs官方并没特别支持typeORM
还是说是建议用官方推荐的egg-sequelize呢？

**Comment by hubcarl** [comment]
这个没有强制，自己根据业务需要引入，你可以自己写一个 egg-typeorm

**Comment by hubcarl** [comment]
从社区了解，大家目前用的多是 egg-sequelize
