### ISSUE TITLE
服务器渲染有内存溢出，请问怎样解决？

### ISSUE THREAD

**Issue by Imprevia** [easy-team/egg-vue-typescript-boilerplate#7]
![tim 20181024182238](https://user-images.githubusercontent.com/10266813/47424243-cfcc6280-d7b9-11e8-8495-b83baca9f5eb.png)

做了一个压力测试，发现有内存溢出，是vue-router内存溢出

**Comment by hubcarl** [comment]
@Imprevia   store 和  vue-router 实例必须以函数返回且在 render context 内部创建 ，否则容易造成单例和内存泄漏问题,  参考 https://github.com/easy-team/egg-vue-webpack-boilerplate/blob/feature/green/spa/app/web/framework/app.js
