### ISSUE TITLE
/login报错

### ISSUE THREAD

**Issue by WinneShen** [easy-team/egg-vue-typescript-boilerplate#8]
给登录页加上路由后，登录页依旧报错。
在我自己的项目里，使用renderClient也报错。
报错内容：render function or template not defined in component: anonymous

    "egg-view-vue-ssr": "^3.0.5",
    "egg-webpack": "^4.4.9",
    "egg-webpack-vue": "^2.0.2",
    "vue": "^2.5.21",
    "vue-property-decorator": "^7.2.0",
    "vue-router": "^3.0.2",
    "vuex": "^3.0.1",
    "vuex-class": "^0.3.1",
    "vuex-router-sync": "^5.0.0"

**Comment by hubcarl** [comment]
login demo 代码后续调整过，没有来得及修改，现在骨架例子为了更符合展示，已经做了调整，没有这个例子
